### PR TITLE
Ajouts des tests unitaires

### LINKED ISSUE #6: [Feature]: Ajouts des tests unitaires pour OxygenCS
### Informations sur le feature

Voir [l'énoncé de laboratoire 2](https://ena.etsmtl.ca/pluginfile.php/1938590/mod_resource/content/4/Laboratoire2_%C3%89nonc%C3%A9_H24.pdf).

Dans cette deuxième phase de votre projet, vous devez mettre en place [...] l’automatisation des tests d'OxygenCS.

Vous devrez aussi faire des modifications à l’application Oxygène CS, incluant l’ajout de tests unitaires.

### PR DESCRIPTION
**Pull request by turbowarrior**
### Rules

Make sure that your pull request contains the following:

- [x] Good branch naming convention (e.g. `feature/` or `doc/` prefixes)
- [x] Relevant Issue related to the PR
- [x] Add the reviewer
- [x] Add the fields to the pull request (e.g. project, labels)
  

## Describe the change (new feature or documentation)
Ajouts des tests unitaires dans le projet oxygeneCS

Cela comprend 3 tests unitaires:
- TurnOnHeater
- TurnOnAC
- SaveDataToDB

D'autres tests peuvent être ajoutés en temps et lieux.

### CODE REVIEW

**Review by MarcAndreDespins — APPROVED** [review]
good job

**Comment by turbowarrior** [comment]
Adding comments to

**Comment by turbowarrior** [comment]
Populate the data

**Comment by turbowarrior** [comment]
Thank you

**Pull request merged**
